
name: Feature / Enhancement Request
description: Suggest an idea/enhancement for this project
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: "Please provide an overview of the feature or enhancement you would like Waltz to incorporate"
      placeholder: "e.g.: add ability to export flow data in XYZ format"
    validations:
      required: true
  - type: dropdown
    id: resourcing
    attributes:
      label: Resourcing
      description: Are you able/planning to contribute the feature to Waltz
      options:
        - We would like to add this request to the Waltz team's feature backlog
        - We would like to collaborate on this feature
        - We intend to contribute this feature
    validations:
      required: true
