# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

uses: Harmon758/postgresql-action@v1.0.0
  with:
    # Version of PostgreSQL to use
    # POSTGRES_DB - name for the default database that is created
    postgresql db: waltz
    # POSTGRES_USER - create the specified user with superuser power
    postgresql user: postgres
    # POSTGRES_PASSWORD - superuser password
    postgresql password: 
    
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B -s .build.settings.xml -Pbuild-postgres,waltz-postgres,ci clean package;
